apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      image:
        imageType: distroless
    discoverySelectors:
    - matchLabels:
        istio-discovery: enabled
kind: ConfigMap
metadata:
  name: istio-asm-managed-rapid
  namespace: istio-system
