apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: onlineboutique
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/rick-c-goog/acm-workshop-onlineboutique-repo
    revision: HEAD
    branch: main
    dir: staging
    auth: none
